### ISSUE TITLE
Error while trying to call a shortcodes directory instead of Shortcodes.

### ISSUE THREAD

**Issue by aradianoff** [Sommerregen/grav-plugin-shortcodes#1]
I installed the Shortcuts plugin manually. Got:

```
 FilesystemIterator::__construct(/path-to-my-grav-installation/user/plugins/shortcodes/classes/shortcodes): failed to open dir: No such file or directory
```

And there isn't such a directory. It is named Shortcodes with capital S.

Just changing the `shortcodes` to `Shortcodes` in ln. 144 of `user/plugin/shortcodes/classes/Shortcodes.php` makes it work (or at least to not throw an error)

**Comment by Sommerregen** [comment]
Damn, you are right! :-) Thanks, I will update the code and release a new version.

Further, I also forgot to mention somewhere, that the "assets" shortcode is only working properly on uncached pages. However caching with [AdvancedPageCache](https://github.com/getgrav/grav-plugin-advanced-pagecache) will help. But [Assets](https://github.com/getgrav/grav-plugin-assets) has the same problem...
I have an idea in mind to solve the issue ingeniously, hopefully available in the fixed version, too.
