### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [Sommerregen/grav-plugin-shortcodes#2]
The plugin Shortcodes can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/shortcodes`) and click on _Save_, there's the following error:

> **Validation failed:** options is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, Shortcodes v1.1.0

**Comment by Sommerregen** [comment]
Thanks! :-) :+1:

**Comment by Sommerregen** [comment]
Fixed in release v1.2.0
